repos:
  - repo: local
    hooks:
      - id: commit-msg-check
        name: Commit message convention check
        entry: bash scripts/commit_msg_checker.sh
        language: system
        stages: [commit-msg]
        pass_filenames: true
