name: 🚀 Tool Request
description: Suggest a new tool or improvement
title: "[Tool]: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a tool! Please complete the following.

  - type: input
    id: feature-description
    attributes:
      label: Feature description
      description: What would you like to see added?
      placeholder: "Add support for..."

    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this tool important?
      placeholder: "This would help users by..."

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Are there any alternative solutions you considered?
      placeholder: "Alternatively, we could..."
