name: Deploy Python Package

on:
  push:
    branches:
      - main
    paths:
      - 'scripts/deploy-package.sh'
      - 'pyproject.toml'
      - 'README.md'
      - '.github/workflows/publish-package.yml'
      - binance_mcp_server/**
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Check Python version
        run: python --version
    
      - name: Install uv
        run: pip install uv
    
      - name: Check uv version
        run: uv --version

      - name: Set environment variables
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          echo "PYPI_TOKEN is set"

      - name: Make deploy script executable
        run: chmod +x scripts/deploy-package.sh

      - name: Deploy package
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: ./scripts/deploy-package.sh